language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - rbx-2.0.0
  - rbx-2.1.1
  - macruby
allow_failures:
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  - rvm: jruby-20mode
