language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.7
  - 2.2.0
  - 2.2.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: rbx-2
